# Generated by Django 4.1.11 on 2023-10-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_alter_note_author_alter_note_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
